---
title: "data cleaning 2"
author: "王正評"
date: "9/25/2019"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

```


```{r, include=FALSE}

library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)

```


## gather

```{r}

df_gatherExample <- data.frame(
  country=c("A","B","C"),
  `1999`=c("0.7k","37k","212k"),
  `2000`=c("2k","80k","213k"),
  check.names = F
)

```

```{r}

df_gatherExample
gather(df_gatherExample,
       `1999`,`2000`,
       key="年份",value="人口")

```

```{r}
library(readr)
collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")
```


```{r}

# gather中的變數選擇可使用select helpers

gather(collegeData, 
       contains("生"), 
       key = "類別", value = "人數")


gather(collegeData, 
       ends_with("生"), 
       key = "類別", value = "人數")

```


```{r}

library(readr)
df_taoyuanMarriage <- read_csv("https://data.tycg.gov.tw/opendata/datalist/datasetMeta/download?id=f95d1a33-ec56-44c5-a9ec-3afba8157e39&rid=fd2070ef-7431-4f9c-bc3a-82d7bfbcd2fb")

```

```{r}

gather(df_taoyuanMarriage, 
       -月份區域別, 
       key = "月份", value = "對數") %>%
  group_by(月份) %>%
  summarise(總對數 = sum(對數))


```

```{r}

df_taoyuanMarriage %>% 
  gather(-月份區域別, 
       key = "月份", value = "對數")

```


## spread

```{r}

df_spreadExample <- data.frame(
  id = c(1,1,1,2,2,2),
  var = c("花朶萼片長度", "學名", "總類數"),
  value = c(5.1, "setosa", 1, 
            7.0, "versicolor", 2))

```

```{r}

df_spreadExample

spread(df_spreadExample, 
       var, value)

```

```{r}

df_twbankExchangeRate <- read_csv("http://www.bot.com.tw/Govinfo/opendata/csv/151/20180101-20181231-FXCRT.csv")

```

```{r}

df_twbankExchangeRate %>%
  select(-即期賣出匯率) %>%
  spread(幣別, 即期買入匯率)

```

```{r}

df_twbankExchangeRate
# 調整資料屬性

df_twbankExchangeRate %>%
  transmute(日期 = lubridate::ymd(日期), 
            幣別 = as.factor(幣別), 
            即期買入匯率 = as.double(即期買入匯率), 
            即期賣出匯率 = as.double(即期賣出匯率)
            ) -> df_twbankExchangeRate_1

df_twbankExchangeRate_1

```




```{r}

library(readr)
taifex_open_data <- read_csv("http://www.taifex.com.tw/data_gov/taifex_open_data.asp?data_name=DailyForeignExchangeRates", 
    locale = locale(encoding = "BIG5"))
View(taifex_open_data)


```

```{r}

taifex_open_data

names(taifex_open_data)

```

```{r}

```



