---
title: "2019-10-09"
author: "林茂廷"
date: "9/11/2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext); library(colorspace); library(scales);
library(sf)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

# 5.5.2

```{r}
# 輸入各自county polygon座標資訊
outer <-     
  rbind( # 外圍
    c(1,5),
    c(2,1),
    c(5,1),
    c(5,5),
    c(1,5)) # 必需自行輸入起點close it

hole <-
  rbind( # 洞
    c(2,4),
    c(3,2),
    c(4,3),
    c(2,4))  # 必需自行輸入起點close it
  
outer2 <- outer + 12
hole2 <- hole + 12

```


```{r}
# 架構每個county的sfg (sf geometry)
sfg_county1 <- st_polygon(list(
  outer,hole
))
sfg_county2 <- st_polygon(list(
  outer2, hole2
))
```

```{r}
# sfg 堆成sfc
sfc_county12column <- st_sfc(sfg_county1,sfg_county2)
```

# 5.5.3

```{r}
# 各county的基本資訊
df_county12 <- data.frame(
  name=c("county1","county2"),
  population=c(100,107)
)

df_county12
```

```{r}
# df 添加geometry column
df_county12 %>%
  st_set_geometry(sfc_county12column) -> df_county12

df_county12 %>% names
```

```{r}
class(df_county12)
```


```{r}
df_county12 %>% 
  ggplot+geom_sf(
    aes(
      fill=population
    )
  )+
  geom_sf_text(
    aes(label=name)
  )
```

```{r}
df_county12
```

```{r}
dir.create("county12")
write_sf(df_county12,"county12/county12.shp")
```

# tpe mrt

```{r}
load(url("https://www.dropbox.com/s/uvco1te2kbs6o01/MRT_Taipei.Rda?dl=1"))
```

```{r}
sf_mrt_tpe %>% View
```

```{r}
sf_mrt_tpe %>%
  filter(
    stringr::str_detect(經過路線,"BL")
  ) ->
  sf_mrt_tpe_bl
```

```{r}
sf_mrt_tpe_bl %>% 
  View
```


```{r}
sf_mrt_tpe_bl %>%
  st_coordinates() %>%
  st_linestring() -> sfg_mrt_bl

sfg_mrt_bl %>%
  ggplot()+geom_sf()
```

```{r}
sf_mrt_tpe_bl %>%
  mutate(
    站號=stringr::str_extract(
      經過路線, "(?<=(BL))[:digit:]+"
    ) # 取出那些數字（那些指它們前面有BL字眼）
  ) %>%
  arrange(站號)-> sf_mrt_tpe_bl

sf_mrt_tpe_bl %>% View
```

```{r}
sf_mrt_tpe_bl %>%
  st_coordinates() %>%
  st_linestring() -> sfg_mrt_bl2 # 捷運板南的simple feature geometry

sfg_mrt_bl2 %>%
  ggplot()+geom_sf()
```

```{r}
df_mrt <- data.frame(
  linename="BL"
)
sfg_mrt_bl2 %>%
  st_sfc() -> sfc_mrt_bl2

df_mrt %>%
  st_set_geometry(sfc_mrt_bl2) -> 
  df_mrt

df_mrt
```

```{r}
sf_mrt_tpe %>%
  st_crs -> mrt_crs

df_mrt %>%
  st_set_crs(mrt_crs) ->
  df_mrt

df_mrt
```


```{r}
read_sf("/Users/martin/Desktop/GitHub/Courses/course-108-1-inclass-datavisualization/mapdata201907311006 /COUNTY_MOI_1080726.shp") -> 
  sf_taiwan
```

```{r}
sf_taiwan
```

```{r}
sf_taiwan %>%
  ggplot()+
  geom_sf()
```

