---
title: "2019-10-09"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r basic setup, message=FALSE, echo=F, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext); library(colorspace); library(scales); library(magick); library(sf); library(rmapshaper); library(osmdata); library(plotly); library(leaflet); 

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)

source("https://www.dropbox.com/s/mdx4777ugnluspz/webApplications.R?dl=1")
```

## Create 

```{r}
dir.create(
  "./1211"
)
download.file("https://raw.githubusercontent.com/tim8537099/course-108-1-inclass-datavisualization/master/example/tet.Rmd",
              destfile="1211/tet.Rmd"
)
download.file("https://github.com/tim8537099/course-108-1-inclass-datavisualization/blob/master/example/plot_us.Rda?raw=true",
              destfile="1211/plot_us.Rda"
)

file.edit("1211/tet.Rmd")
```



## Create a New Project

```{r}
webapp_project_create(
  dirlib="./1211/webapp",
  overwrite=T
)
```

