---
title: "2019-10-09"
author: "林茂廷"
date: "9/11/2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext); library(colorspace); library(scales)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```


## How to replicate

```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework3/graphData_homework3_005.Rda?raw=true"))
#load("graphData_homework3_005.Rda")
c('area','age','性別','n')->names(graphdata[[1]])
## ----graph, echo=T, eval=T-----------------------------------------------
library(ggalluvial)
#is_alluvia_form(as.data.frame(graphdata), axes = 1:3, silent = TRUE)
                                          finalplot<-ggplot(as.data.frame(graphdata),
       aes(y = n, axis1 = age, axis2 =area)) +
  geom_alluvium(aes(fill=性別), width = 1/10) +
  geom_stratum(width = 1/10, fill = "gray", color = "white") +
  geom_label(stat = "stratum", label.strata = TRUE) +scale_x_discrete(limits = c("age", "area"), expand = c(.1, .1)) +scale_fill_brewer(type = "qual", palette = "Set2")+
ggtitle("2018年登革熱病例統計")+ylab('確診人數')+theme(title = element_text(family ="QYuan" ))
finalplot                                   
```

## 4.1.3

```{r}
library(readr)
library2014 <- read_csv("https://www.dropbox.com/s/999hy0u1y98y6ep/library2014.csv?dl=1")

graphList <- list()

library2014 %>%
  mutate(
    學院=reorder(學院,學號,length,order=T),
    讀者年級=reorder(讀者年級,讀者年級, order=T)
  ) -> library2014

library2014 %>% 
  ggplot()-> graphList$圖書_ggplotOnly

graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院), fill="#5A99B3", width=0.7
    )
```

geom_bar
```{r}
graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院) # 預設 stat="count"
  )
```

stat_count
```{r}
graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院), 
    geom="bar" # geom_bar內訂會取 count來當y
  )
```

```{r}
graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院,y=stat(prop)), 
    geom="bar" # geom_bar內訂會取 count來當y
  )
```

設定大家同group
```{r}
graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院,y=stat(prop),group="全校"), 
    geom="bar" # geom_bar內訂會取 count來當y
  )
```

```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,y=stat(prop),group="全校"), 
    stat="count" 
  )
```

## override geom

```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,y=stat(prop),group="全校"), 
    stat="count" 
  )+
  stat_count(
    aes(x=學院,y=stat(prop),group="全校", label=round(stat(prop),2)),
    geom="text"
  )
```

## override stat

```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,y=stat(prop),group="全校"), 
    stat="count" 
  )+
  geom_text(
    aes(x=學院,y=stat(prop),group="全校",label=round(stat(prop),2)
        ),
    stat="count"
  )
```





## override geom: nudge_y

```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,y=stat(prop),group="全校"), 
    stat="count" 
  )+
  stat_count(
    aes(x=學院,y=stat(prop),group="全校", label=round(stat(prop),2)),
    geom="text", nudge_y=-0.1
  )
```

## override stat: nudge_y

```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,y=stat(prop),group="全校"), 
    stat="count" 
  )+
  geom_text(
    aes(x=學院,y=stat(prop),group="全校",label=round(stat(prop),2)
        ),
    stat="count", nudge_y=-0.1
  )
```

## stat_function

```{r}
df_x <- data.frame(
  x=rnorm(500,mean=2,sd=1)
)
df_x$x %>% head()
```

```{r}
df_x %>%
  ggplot()+
  geom_histogram(
    aes(x=x)
  )
```


````{r}
df_x %>%
  ggplot(aes(x=x))+
  geom_histogram(
    aes(y=stat(density))
  )+
  stat_function(
    fun=dnorm, args = list(mean=2, sd=1) # dnorm 為常態分配density函數
  )
```

```{r}
market_demand <- function(x, a=1, b=-1){
  return(a+b*x)
}

market_supply <- function(x, a=0, b=1){
  return(a+b*x)
}

df_grids <- 
  data.frame(
    x=seq(0,1,by=0.2))
df_grids$x
```


```{r}
df_grids %>%
  ggplot(aes(x=x))+
  stat_function(
    fun="market_demand"
  )+
  stat_function(
    fun="market_supply"
  )+
  stat_function(
    fun="market_supply",
    args = list(b=0.8), color="red"
  )+
  scale_y_continuous(
    limits = c(0,1)
  )+
  labs(
    x="Quantity", y="Price"
  ) -> graphList$demand_supply

graphList$demand_supply
```


## surplus

```{r}
df0<- data.frame(
      x=seq(0.25,0.5,by=0.01),
      y=seq(0.25,0.5,by=0.01)
    )

df0 %>% 
  ggplot(aes(x=x,y=y))+
  stat_summary(
   fun.ymin= function(y) market_demand(y),
    fun.ymax= function(y) market_supply(y),
   geom="ribbon"
   )
  
```

```{r}
graphList$demand_supply+
  stat_summary(
    data=df0,
    mapping=aes(x=x,y=y),
   fun.ymin= function(y) market_demand(y),
    fun.ymax= function(y) market_supply(y),
   geom="ribbon"
   )  

```


```{r}
graphList$demand_supply+
  geom_ribbon(
    data=data.frame(
      x=seq(0.25,0.5,by=0.01)
    ),
    aes(y=x),
    stat="summary", 
    fun.ymin= function(y) market_demand(y),
    fun.ymax= function(y) market_supply(y),
    alpha=0.3
  )
```

