---
title: "每週一圖作業資料檔"
output: html_document
params:
  組員: ["王正評"]  
  學號: ["710761105"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```



#### 資料處理
  
```{r data cleaning, echo=TRUE, eval=T}

library(magick)

graphListD <- list()

graphListD$cakeResume_Horace <- 
  data.frame(
    start = c(20, 57, 78, 137, 152), 
    end = c(66, 67, 135, 148, 156), 
    floor = c(2, 2, 2, 2, 2), 
    celling = c(2.8, 3, 3, 3, 3), 
    類別 = c("學業", "工讀", "正職", "工讀", "正職")
  )


graphListD$breaksdate <- 
  c(20, 57, 78, 137, 152, 66, 67, 135, 148, 156)


image_read("https://www.ntue.edu.tw/images/logo.png") -> 
  graphListD$ntue

graphListD$ntue %>% 
  as.raster() -> 
  graphListD$ntue_raster


#2008 ~ 2012  
#Oct 2011 ~ Aug 2012 
#Jul 2013 ~ Apr 2018
#Jun 2018 ~ May 2019  
#Sep 2019 ~ Present

#save(graphListD, file="homework6.Rda")

```

```{r}

#image_read() -> 
#  graphListD$XXX

#graphListD$XXX %>% 
#  as.raster() ->
#  graphListD$XXX_raster

```
