---
title: "每週一圖作業繪圖說明檔"
output: html_document
params:
  組員: ["王正評"]  
  學號: ["710761105"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```


#### 繪圖程式

```{r graph, echo=T, eval=T}

load("homework4.Rda")

graphListP <- list()



graphListD$Case_10_result_eV %>% 
  ggplot(
    aes(
      x = 六都, 
      y = `同意比例（同意票／有效票）`
    )
  ) + 
  geom_col(
    aes(
      alpha = `同意比例（同意票／有效票）`
    ), 
    width = 0.5, 
    fill = "#FF72C7"
  ) -> 
  graphListP$base

graphListP$base + 
  coord_flip() +  
  scale_x_discrete(
    limits = c("高雄市", "臺南市", "臺中市", "桃園市", "新北市", "臺北市")
  ) + 
  scale_y_continuous(
    limits = c(0, 0.75), 
    labels = function(x) x*100
  ) + 
  scale_alpha(
    range = c(1, 0.2)
  ) -> 
  graphListP$adjust_scale
  
graphListP$adjust_scale + 
  geom_text(
    aes(
      label = str_c(
        round(`同意比例（同意票／有效票）`*100, 2),      #round(四捨五入至小數第一位)
        "%"
      )
    ), 
    size = 5, 
    hjust = 1.1, 
    color = "#666666"
  ) + 
  labs(
    title = "你是否同意民法婚姻規定應限定在一男一女的結合 ?", 
    y = "同意比例（同意票／有效票）％"
  ) + 
  theme_bw() + 
  #清理軸線
  theme(
    legend.position = "none", 
    axis.title.y = element_blank(), 
    axis.line = element_blank(), 
    axis.ticks = element_blank()
  ) + 
  #清理輔助線
  theme(
    panel.border = element_blank(), 
    panel.grid.minor = element_blank(), 
    panel.grid.major.y = element_blank()
  ) + 
  #調整文字
  theme(
    plot.title = element_text(hjust = 0.5), 
    axis.text.y = element_text(
      size = 10, 
      hjust = 30, 
      color = "black"
    ), 
    axis.text.x = element_text(color = "#666666"), 
    axis.title.x = element_text(colour = "#666666")
  ) + 
  geom_hline(
    aes(yintercept = 0)
  ) -> 
  graphListP$end

graphListP$end

```

#### 設計說明
說明想傳達的訊息（必要）及設計想法（非必要）。寫在***下一行。

*** 
公投案第10案：你是否<code>同意</code>民法婚姻規定<code>應限定在一男一女</code>的結合？

<ol>
  <li>六都的同意比例皆超過5成，顯示台灣社會對於性別的觀念仍趨保守。</li>
  <li>可看出雙北對於性別的觀念較其他四都開放，臺北市的同意比例甚至掉到7成以下。</li>
  <li>可看出愈往北部，性別觀念有愈趨成熟的趨勢。</li>
</ol>


