---
title: "每週一圖作業資料檔"
output: html_document
params:
  組員: ["王正評"]  
  學號: ["710761105"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

#### 資料處理
  
```{r data cleaning, echo=TRUE, eval=T}

graphListD <- list()

graphListD$Case_10_result <- 
  read_csv("http://data.cec.gov.tw/%E5%85%A8%E5%9C%8B%E6%80%A7%E5%85%AC%E6%B0%91%E6%8A%95%E7%A5%A8%E8%A8%88%E7%A5%A8%E7%B5%90%E6%9E%9C/Case_10_result.csv")



graphListD$Case_10_result %>%
  select(
    公投案編號, 
    縣市, 
    同意票數, 
    有效票數
  ) %>%
  slice(
    14:22
  ) %>%
  filter(
    有效票數 > 200000
  )  %>% 
  transmute(
    公投案編號, 
    六都 = as.factor(縣市), 
    同意票數 = as.integer(同意票數), 
    有效票數 = as.integer(有效票數), 
    `同意比例（同意票／有效票）` = 同意票數/有效票數, 
  ) ->
  graphListD$Case_10_result1
 
graphListD$Case_10_result1 %>% 
  mutate(
    六都 = factor(
      六都, 
      levels = c(
        "臺北市", "新北市", "桃園市", "臺中市", "臺南市", "高雄市"
      )
    )
  ) -> 
  graphListD$Case_10_result_eV

```

