---
title: "每週一圖作業繪圖說明檔"
output: html_document
params:
  組員: ["王正評"]  
  學號: ["710761105"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```



#### 繪圖程式

```{r graph, echo=T, eval=T}

load("homework6.Rda")

library(magick)

graphListP <- list()



ggplot() + 
  geom_rect(
    mapping = aes(
      xmin = 20, 
      xmax = 156, 
      ymin = 2, 
      ymax = 3
    ), 
    fill = "#DDDDDD"
  ) + 
  scale_x_continuous(
    limits = c(10, 190), 
    breaks = graphListD$breaksdate
  ) + 
  scale_y_continuous(
    limits = c(1, 4)
  ) -> 
  graphListP$timeaxis_base
  
graphListP$timeaxis_base + 
  geom_rect(
    data = graphListD$cakeResume_Horace %>% 
      filter(類別 != "學業"), 
    mapping = aes(
      xmin = start, 
      xmax = end, 
      ymin = floor, 
      ymax = celling, 
      fill = 類別
    )
  ) + 
  geom_rect(
    data = graphListD$cakeResume_Horace %>% 
      filter(類別 == "學業"), 
    mapping = aes(
      xmin = start, 
      xmax = end, 
      ymin = floor, 
      ymax = celling
    ), 
    fill = "#FF3333", 
    alpha = 0.4
  ) ->
  graphListP$timeaxis_SandW

qualitative_hcl(n = 2, h = c(150, 240), c = 100, l = 60, register = "godPaltte-Qua_GB")

graphListP$timeaxis_SandW + 
  scale_fill_discrete_qualitative(palette = "godPaltte-Qua_GB") -> 
  graphListP$timeaxis_SandW1



graphListP$timeaxis_SandW1 + 
  annotation_raster(
    raster = graphListD$ntue_raster, 
    xmin = 38-36/2, xmax = 38+36/2, 
    ymin = 3.1-0.3, ymax = 3.1+0.3
  ) + 
  #北教大
  annotate(
    "text", x = 39, y = 2.4, 
    label = "數位科技設計學系", 
    size = 10/.pt
  ) + 
  #ATT文創
  annotate(
    "text", x = 62.5, y = 1.8, 
    label = "ATTShowBox文創", 
    size = 10/.pt
  ) + 
  annotate(
    "text", x = 62.5, y = 1.8-0.2, 
    label = "行政藝術工讀生", 
    size = 10/.pt
  ) + 
  #PIXNET
  annotate(
    "text", x = 107, y = 2.55, 
    label = "PIXNET優像數位媒體科技", 
    size = 10/.pt
  ) + 
  annotate(
    "text", x = 107, y = 2.55-0.2, 
    label = "資深網頁設計師", 
    size = 10/.pt
  ) + 
  #coffee
  annotate(
    "text", x = 143, y = 1.8, 
    label = "Maison de gigi coffee", 
    size = 10/.pt
  ) + 
  annotate(
    "text", x = 143, y = 1.8-0.2, 
    label = "咖啡師（日本）", 
    size = 10/.pt
  ) + 
  #玉山
  annotate(
    "text", x = 172, y = 2.55, 
    label = "ESUN BANK 玉山銀行", 
    size = 10/.pt
  ) + 
  annotate(
    "text", x = 172, y = 2.55-0.2, 
    label = "資深網頁設計師", 
    size = 10/.pt
  ) + 
  theme(
    aspect.ratio = 1/2.5
  ) -> 
  graphListP$timeaxis_SandW2



graphListP$timeaxis_SandW2 + 
  theme(
    legend.direction = "horizontal", 
    legend.position = c(0.85, 0.85), 
    legend.title = element_blank(), 
    legend.background = element_blank()
  ) + 
  scale_x_continuous(
    limits = c(10, 190), 
    breaks = c(24, 72, 132, 144), 
    labels = c("2009", "2013", "2018", "2019")
  ) + 
  #清理軸線
  theme(
    axis.title = element_blank(), 
    axis.ticks.y = element_blank(), 
    axis.text.y = element_blank(), 
    axis.line.y = element_blank()
  ) + 
  theme(
    axis.line.x = element_line(
      color = "#DDDDDD", 
      size = 2, 
      arrow = arrow()
    ), 
    axis.ticks.x = element_line(color = "#666666"), 
    axis.text.x = element_text(color = "#666666")
  ) -> 
  graphListP$timeaxis_end


font_add("標楷體", "kaiu.ttf")

graphListP$timeaxis_end + 
  labs(
    title = "經 歷"
  ) + 
  theme(
    title = element_text(
      family = "標楷體", 
      size = 60/.pt
    )
  ) -> 
  graphListP$timeaxis_endwT

graphListP$timeaxis_endwT
  
```



#### 設計說明
說明想傳達的訊息（必要）及設計想法（非必要）。寫在***下一行。

*** 
Resume Link: <https://www.cakeresume.com/lan-horace>

以時間軸的方式簡略的呈現出 Horace Lan 的個人經歷。
在此可看出她畢業於北教大的數位科技設計學系，以及她曾經的工作職位和年資，
有助於雇主快速的了解 Horace Lan 是否為他想找的員工。 


