---
title: "Untitled"
author: "jacky wang"
date: "2019/12/7"
output: html_document
---

```{r setup, include=FALSE}

rm(list = ls())

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

# windows檔名不要有"-"號

```

```{r package, include=FALSE}

library(readr) #資料匯入
library(dplyr) #資料整理（slice、select、filter、mutate）
library(tidyr) #資料整理（gather、spread）
library(stringr) #處理字串
library(lubridate) #時間資料處理（ymd）
library(ggplot2) #作圖
library(magrittr) # %<>%
library(showtext) #從字型檔讀取字型，並在繪圖時使用

library(grDevices) #不同色彩空間的十六進制代碼呈現（#598C73）
library(scales) #show_col()：螢幕立即顯示顏色
library(colorspace) #調色盤選擇及ggplot應用工具
library(shiny) #支援套件
library(shinyjs) #支援套件

library(sf)
library(osmdata)
library(rvest)
library(plotly)
library(emojifont)
source(file = "D:/Users/User/Documents/GitHub/Rfunction/osmGeomRename.R")

```



```{r graph 1}

load("homework7.Rda")
data(world, package = "spData")

godPlot <- list()

world %>% 
  filter(
    !continent %in% c("Antarctica", "Seven seas (open ocean)") 
  ) %>%
  ggplot() + 
  geom_sf(
    color = "white"
  ) + 
  geom_sf(
    data = godData$world_PW, 
    color = "white", 
    fill = "forestgreen"
  ) + 
  theme_bw()  + 
  scale_x_continuous(
    expand = expand_scale(add = 0)
  ) -> 
  godPlot$plot_base

godPlot$plot_base

```

```{r graph 2}

godPlot$plot_base + 
  geom_point(
    data = godData$world_centroid1 %>% 
      filter(
        !country_name %in% c("Mali", "Niger")
      ), 
    mapping = aes(
      x = X, 
      y = Y
    ), 
    size = 1
  ) + 
  geom_segment(
    data = godData$seg_left, 
    mapping = aes(
      x = X, xend = X-20, 
      y = Y, yend = Y
    )
  ) + 
  geom_segment(
    data = godData$seg_right, 
    mapping = aes(
      x = X, xend = X+20, 
      y = Y, yend = Y
    )
  ) + 
  geom_segment(
    data = godData$seg_up, 
    mapping = aes(
      x = X, xend = X, 
      y = Y, yend = Y+10
    )
  ) + geom_segment(
    data = godData$seg_down, 
    mapping = aes(
      x = X, xend = X, 
      y = Y, yend = Y-10
    )
  ) -> 
  godPlot$plot_PtSeg

godPlot$plot_PtSeg

```

```{r graph 3}

 godPlot$plot_PtSeg + 
  geom_text(
    data = godData$seg_left %>% 
      filter(
        country_name != "United States"
      ), 
    mapping = aes(
      x = X - 20, 
      y = Y + 7, 
      label = emoji("triangular_flag_on_post")
    ), 
    family = "EmojiOne", 
    color = "red"
  ) + 
  geom_text(
    data = godData$seg_left %>% 
      filter(
        country_name == "United States"
      ), 
    mapping = aes(
      x = X - 20, 
      y = Y + 7, 
      label = str_c(emoji("triangular_flag_on_post"), emoji("triangular_flag_on_post"), emoji("triangular_flag_on_post"), collapse = "")
    ), 
    family = "EmojiOne", 
    color = "red"
  ) + 
  geom_text(
    data = godData$seg_right, 
    mapping = aes(
      x = X + 20, 
      y = Y + 7, 
      label = emoji("triangular_flag_on_post")
    ), 
    family = "EmojiOne", 
    color = "red"
  ) + 
  geom_text(
    data = godData$seg_up, 
    mapping = aes(
      x = X, 
      y = Y + 16, 
      label = emoji("triangular_flag_on_post")
    ), 
    family = "EmojiOne", 
    color = "red"
  ) + 
  geom_text(
    data = godData$seg_down, 
    mapping = aes(
      x = X, 
      y = Y - 10, 
      label = emoji("triangular_flag_on_post")
    ), 
    family = "EmojiOne", 
    color = "red"
  ) -> 
  godPlot$plot_event

godPlot$plot_event

```

```{r graph 4}

godPlot$plot_event + 
  theme(
    panel.border = element_blank(), 
    panel.grid = element_blank(), 
    axis.ticks = element_blank(), 
    axis.title = element_blank(), 
    axis.text = element_blank()
  ) + 
  labs(
    title = "Politics this week", 
    subtitle = "Nov 21st 2019 edition", 
    caption = "Source: The Economist"
  ) + 
  theme(
    panel.background = element_rect(fill = "lightblue"), 
    plot.title = element_text(size = 48/.pt), 
    plot.subtitle = element_text(size = 30/.pt, color = "#888888"), 
    plot.caption = element_text(color = "#888888")
  ) -> 
  godPlot$plot_end

godPlot$plot_end

```

```{r}

#godPlot$plot_end -> flexplot

#save(flexplot, file = "homework7_plot.Rda")

```




