---
title: "homework8 data"
author: "jacky wang"
date: "2019/12/23"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

# windows檔名不要有"-"號

```

```{r package, include=FALSE}

library(readr) #資料匯入
library(dplyr) #資料整理（slice、select、filter、mutate）
library(tidyr) #資料整理（gather、spread）
library(stringr) #處理字串
library(lubridate) #時間資料處理（ymd）
library(ggplot2) #作圖
library(magrittr) # %<>%
library(showtext) #從字型檔讀取字型，並在繪圖時使用

library(grDevices) #不同色彩空間的十六進制代碼呈現（#598C73）
library(scales) #show_col()：螢幕立即顯示顏色
library(colorspace) #調色盤選擇及ggplot應用工具
library(shiny) #支援套件
library(shinyjs) #支援套件

```





# 資料處理

## fb

```{r}

sample(1:20, 10 ,replace = T)

```

```{r}

data_frame(
  活動 = "青銀共賞電影", 
  位置 = "FB", 
  timeStamp = seq.POSIXt(
    from = ymd_h("2019-11-04 12"), 
    to = ymd_h("2019-11-09 00"), 
    by = 12*60*60
  ), 
  點擊數 = c(18, 5, 5, 15, 14, 19, 11, 2, 15, 9), 
  日夜 = c("日", "夜", "日", "夜", "日", "夜", "日", "夜", "日", "夜")
) -> 
  fb_movie

data_frame(
  活動 = "北大玩具節", 
  位置 = "FB", 
  timeStamp = seq.POSIXt(
    from = ymd_h("2019-11-18 12"), 
    to = ymd_h("2019-11-23 00"), 
    by = 12*60*60
  ), 
  點擊數 = c(3, 14, 9, 20, 8, 13, 15, 3, 15, 14), 
  日夜 = c("日", "夜", "日", "夜", "日", "夜", "日", "夜", "日", "夜")
) -> 
  fb_toys

data_frame(
  活動 = "聖誕點燈暨北大管樂節", 
  位置 = "FB", 
  timeStamp = seq.POSIXt(
    from = ymd_h("2019-12-16 12"), 
    to = ymd_h("2019-12-21 00"), 
    by = 12*60*60
  ), 
  點擊數 = c(12, 18, 16, 4, 1, 15, 5, 8, 18, 5), 
  日夜 = c("日", "夜", "日", "夜", "日", "夜", "日", "夜", "日", "夜")
) -> 
  fb_Christmas

```

## web

```{r}

data_frame(
  活動 = "青銀共賞電影", 
  位置 = "web", 
  timeStamp = seq.POSIXt(
    from = ymd_h("2019-11-04 12"), 
    to = ymd_h("2019-11-09 00"), 
    by = 12*60*60
  ), 
  點擊數 = c(16, 16, 3, 14, 9, 3, 14, 1, 15, 5), 
  日夜 = c("日", "夜", "日", "夜", "日", "夜", "日", "夜", "日", "夜")
) -> 
  web_movie

data_frame(
  活動 = "北大玩具節", 
  位置 = "web", 
  timeStamp = seq.POSIXt(
    from = ymd_h("2019-11-18 12"), 
    to = ymd_h("2019-11-23 00"), 
    by = 12*60*60
  ), 
  點擊數 = c(5, 18, 3, 10, 1, 3, 18, 19, 15, 2), 
  日夜 = c("日", "夜", "日", "夜", "日", "夜", "日", "夜", "日", "夜")
) -> 
  web_toys

data_frame(
  活動 = "聖誕點燈暨北大管樂節", 
  位置 = "web", 
  timeStamp = seq.POSIXt(
    from = ymd_h("2019-12-16 12"), 
    to = ymd_h("2019-12-21 00"), 
    by = 12*60*60
  ), 
  點擊數 = c(11, 10, 1, 18, 12, 2,  9, 10, 13, 14), 
  日夜 = c("日", "夜", "日", "夜", "日", "夜", "日", "夜", "日", "夜")
) -> 
  web_Christmas

```

## poster

```{r}

data_frame(
  活動 = "青銀共賞電影", 
  位置 = "poster", 
  timeStamp = seq.POSIXt(
    from = ymd_h("2019-11-04 12"), 
    to = ymd_h("2019-11-09 00"), 
    by = 12*60*60
  ), 
  點擊數 = c(10, 4, 11, 4, 9, 16, 14, 3, 13, 11), 
  日夜 = c("日", "夜", "日", "夜", "日", "夜", "日", "夜", "日", "夜")
) -> 
  poster_movie

data_frame(
  活動 = "北大玩具節", 
  位置 = "poster", 
  timeStamp = seq.POSIXt(
    from = ymd_h("2019-11-18 12"), 
    to = ymd_h("2019-11-23 00"), 
    by = 12*60*60
  ), 
  點擊數 = c(8, 10, 20, 2, 16, 15,  8, 6, 1, 10), 
  日夜 = c("日", "夜", "日", "夜", "日", "夜", "日", "夜", "日", "夜")
) -> 
  poster_toys

data_frame(
  活動 = "聖誕點燈暨北大管樂節", 
  位置 = "poster", 
  timeStamp = seq.POSIXt(
    from = ymd_h("2019-12-16 12"), 
    to = ymd_h("2019-12-21 00"), 
    by = 12*60*60
  ), 
  點擊數 = c(18, 19, 15, 18, 1, 15, 13, 10, 13, 5), 
  日夜 = c("日", "夜", "日", "夜", "日", "夜", "日", "夜", "日", "夜")
) -> 
  poster_Christmas

#save(
#  fb_Christmas, fb_movie, fb_toys, 
#  web_Christmas, web_movie, web_toys, 
#  poster_Christmas, poster_movie, poster_toys, 
#  file = "rda/homework8Data.Rda"
#)

```





# 其他

```{r}

ymd_hms("2019/11/03 14:05:04") %>% 
  date()

ymd_hms("2019/11/03 14:05:04") %>% 
  hour()

str_c(
  ymd_hms("2019/11/03 14:05:04") %>% date(), 
  ymd_hms("2019/11/03 14:05:04") %>% hour(), 
  sep = " "
) %>% 
  ymd_h()

ymd_h("2019-11-03 00")
  


seq.POSIXt(
  from = ymd_h("2019-11-04 00"), 
  to = ymd_h("2019-11-08 12"), 
  by = 12*60*60
)

seq.Date(from = ymd("2019-12-17"),  to = ymd("2019-12-21"), by = "day")

```

## 計算資料筆數

```{r}

godData$website %>% 
  filter(
    `event title` == "青銀共賞電影"
  )

```

```{r count_click}

godData$website %>% 
  filter(
    `event title` == "青銀共賞電影"
  ) %>% 
  mutate(
    日期 = as.factor(date(timestamp)), 
    小時 = hour(timestamp)
  ) %>% 
  filter(
    日期 == "2019-11-08" & 小時 < 12
  ) 

godData$website %>% 
  filter(
    `event title` == "青銀共賞電影"
  ) %>% 
  mutate(
    日期 = as.factor(date(timestamp)), 
    小時 = hour(timestamp)
  ) %>% 
  filter(
    日期 == "2019-11-08" & 小時 >= 12
  )

```

