---
title: "homework8 plot"
author: "jacky wang"
date: "2019/12/25"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

# windows檔名不要有"-"號

```

```{r package, include=FALSE}

library(readr) #資料匯入
library(dplyr) #資料整理（slice、select、filter、mutate）
library(tidyr) #資料整理（gather、spread）
library(stringr) #處理字串
library(lubridate) #時間資料處理（ymd）
library(ggplot2) #作圖
library(magrittr) # %<>%
library(showtext) #從字型檔讀取字型，並在繪圖時使用

library(grDevices) #不同色彩空間的十六進制代碼呈現（#598C73）
library(scales) #show_col()：螢幕立即顯示顏色
library(colorspace) #調色盤選擇及ggplot應用工具
library(shiny) #支援套件
library(shinyjs) #支援套件

```



# data

```{r}

load("rda/homework8Data.Rda")

godPlot <- list()

qualitative_hcl(n = 2, h = c(60, 250), c = 71, l = 78, register = "godPalette_2Qua")

```

#theme

```{r theme}

theme_classic() + 
  theme(
    panel.background = element_rect(fill = "#fffaf4"), 
    axis.title = element_blank(), 
    axis.line.y = element_blank(), 
    axis.text.y = element_blank(), 
    axis.ticks.y = element_blank() 
  ) + 
  theme(
    axis.line.x = element_line(
      arrow = arrow(), 
      size = 2, 
      color = "#dcdcdc"
    ), 
    axis.text.x = element_text(color = "#333333"), 
    axis.ticks.x = element_line(color = "#333333"), 
    legend.background = element_rect(fill = "#fffaf4"), 
    legend.position = "top", 
    legend.title = element_blank(), 
    legend.text = element_text(color = "#333333")
  ) -> 
  theme_god_hw8

```

#fb

```{r}

fb_movie %>% 
  ggplot(
    aes(
      x = timeStamp, 
      y = 點擊數
    )
  ) + 
  geom_line(
    color = "#dcdcdc", 
    size = 2
  ) + 
  geom_point(
    aes(
      color = 日夜
    ), 
    size = 3
  ) + 
  scale_x_datetime(
    breaks = seq.POSIXt(
      from = ymd_h("2019-11-05 00"), 
      to = ymd_h("2019-11-09 00"), 
      by = "day"
    ), 
    labels = c(
      "11/05", "06", "07", "08", "09"
    )
  ) + 
  # 改legend文字
  scale_color_discrete_qualitative(
    palette = "godpalette_2Qua", nmax = 2,    # rev = TRUE: 顛倒顏色
    breaks = c("日", "夜"), 
    labels = c("上半天結算", "下半天結算")
  ) + 
  geom_hline(
    yintercept = 10, 
    color = "#FF8888", 
    linetype = "58"
  ) + 
  annotate(
    "text", x = ymd_h("2019-11-04 18"), y = 11, 
    label = "10次點擊", 
    color = "#FF8888"
  ) + 
  theme_god_hw8 -> 
  godPlot$fbMovieP

fb_toys %>% 
  ggplot(
    aes(
      x = timeStamp, 
      y = 點擊數
    )
  ) + 
  geom_line(
    color = "#dcdcdc", 
    size = 2
  ) + 
  geom_point(
    aes(
      color = 日夜
    ), 
    size = 3
  ) + 
  scale_x_datetime(
    breaks = seq.POSIXt(
      from = ymd_h("2019-11-19 00"), 
      to = ymd_h("2019-11-23 00"), 
      by = "day"
    ), 
    labels = c(
      "11/19", "20", "21", "22", "23"
    )
  ) + 
  # 改legend文字
  scale_color_discrete_qualitative(
    palette = "godpalette_2Qua", nmax = 2,    # rev = TRUE: 顛倒顏色
    breaks = c("日", "夜"), 
    labels = c("上半天結算", "下半天結算")
  ) + 
  geom_hline(
    yintercept = 10, 
    color = "#FF8888", 
    linetype = "58"
  ) + 
  annotate(
    "text", x = ymd_h("2019-11-18 18"), y = 11, 
    label = "10次點擊", 
    color = "#FF8888"
  ) + 
  theme_god_hw8 -> 
  godPlot$fbToysP

fb_Christmas %>% 
  ggplot(
    aes(
      x = timeStamp, 
      y = 點擊數
    )
  ) + 
  geom_line(
    color = "#dcdcdc", 
    size = 2
  ) + 
  geom_point(
    aes(
      color = 日夜
    ), 
    size = 3
  ) + 
  scale_x_datetime(
    breaks = seq.POSIXt(
      from = ymd_h("2019-12-17 00"), 
      to = ymd_h("2019-12-21 00"), 
      by = "day"
    ), 
    labels = c(
      "12/17", "18", "19", "20", "21"
    )
  ) + 
  # 改legend文字
  scale_color_discrete_qualitative(
    palette = "godpalette_2Qua", nmax = 2,    # rev = TRUE: 顛倒顏色
    breaks = c("日", "夜"), 
    labels = c("上半天結算", "下半天結算")
  ) + 
  geom_hline(
    yintercept = 10, 
    color = "#FF8888", 
    linetype = "58"
  ) + 
  annotate(
    "text", x = ymd_h("2019-12-16 18"), y = 11, 
    label = "10次點擊", 
    color = "#FF8888"
  ) + 
  theme_god_hw8 -> 
  godPlot$fbChristmasP

```

# web

```{r}

web_movie %>% 
  ggplot(
    aes(
      x = timeStamp, 
      y = 點擊數
    )
  ) + 
  geom_line(
    color = "#dcdcdc", 
    size = 2
  ) + 
  geom_point(
    aes(
      color = 日夜
    ), 
    size = 3
  ) + 
  scale_x_datetime(
    breaks = seq.POSIXt(
      from = ymd_h("2019-11-05 00"), 
      to = ymd_h("2019-11-09 00"), 
      by = "day"
    ), 
    labels = c(
      "11/05", "06", "07", "08", "09"
    )
  ) + 
  # 改legend文字
  scale_color_discrete_qualitative(
    palette = "godpalette_2Qua", nmax = 2,    # rev = TRUE: 顛倒顏色
    breaks = c("日", "夜"), 
    labels = c("上半天結算", "下半天結算")
  ) + 
  geom_hline(
    yintercept = 10, 
    color = "#FF8888", 
    linetype = "58"
  ) + 
  annotate(
    "text", x = ymd_h("2019-11-04 18"), y = 11, 
    label = "10次點擊", 
    color = "#FF8888"
  ) + 
  theme_god_hw8 -> 
  godPlot$webMovieP

web_toys %>% 
  ggplot(
    aes(
      x = timeStamp, 
      y = 點擊數
    )
  ) + 
  geom_line(
    color = "#dcdcdc", 
    size = 2
  ) + 
  geom_point(
    aes(
      color = 日夜
    ), 
    size = 3
  ) + 
  scale_x_datetime(
    breaks = seq.POSIXt(
      from = ymd_h("2019-11-19 00"), 
      to = ymd_h("2019-11-23 00"), 
      by = "day"
    ), 
    labels = c(
      "11/19", "20", "21", "22", "23"
    )
  ) + 
  # 改legend文字
  scale_color_discrete_qualitative(
    palette = "godpalette_2Qua", nmax = 2,    # rev = TRUE: 顛倒顏色
    breaks = c("日", "夜"), 
    labels = c("上半天結算", "下半天結算")
  ) + 
  geom_hline(
    yintercept = 10, 
    color = "#FF8888", 
    linetype = "58"
  ) + 
  annotate(
    "text", x = ymd_h("2019-11-18 18"), y = 11, 
    label = "10次點擊", 
    color = "#FF8888"
  ) + 
  theme_god_hw8 -> 
  godPlot$webToysP

web_Christmas %>% 
  ggplot(
    aes(
      x = timeStamp, 
      y = 點擊數
    )
  ) + 
  geom_line(
    color = "#dcdcdc", 
    size = 2
  ) + 
  geom_point(
    aes(
      color = 日夜
    ), 
    size = 3
  ) + 
  scale_x_datetime(
    breaks = seq.POSIXt(
      from = ymd_h("2019-12-17 00"), 
      to = ymd_h("2019-12-21 00"), 
      by = "day"
    ), 
    labels = c(
      "12/17", "18", "19", "20", "21"
    )
  ) + 
  # 改legend文字
  scale_color_discrete_qualitative(
    palette = "godpalette_2Qua", nmax = 2,    # rev = TRUE: 顛倒顏色
    breaks = c("日", "夜"), 
    labels = c("上半天結算", "下半天結算")
  ) + 
  geom_hline(
    yintercept = 10, 
    color = "#FF8888", 
    linetype = "58"
  ) + 
  annotate(
    "text", x = ymd_h("2019-12-16 18"), y = 11, 
    label = "10次點擊", 
    color = "#FF8888"
  ) + 
  theme_god_hw8 -> 
  godPlot$webChristmasP

```

# Poster

```{r}

poster_movie %>% 
  ggplot(
    aes(
      x = timeStamp, 
      y = 點擊數
    )
  ) + 
  geom_line(
    color = "#dcdcdc", 
    size = 2
  ) + 
  geom_point(
    aes(
      color = 日夜
    ), 
    size = 3
  ) + 
  scale_x_datetime(
    breaks = seq.POSIXt(
      from = ymd_h("2019-11-05 00"), 
      to = ymd_h("2019-11-09 00"), 
      by = "day"
    ), 
    labels = c(
      "11/05", "06", "07", "08", "09"
    )
  ) + 
  # 改legend文字
  scale_color_discrete_qualitative(
    palette = "godpalette_2Qua", nmax = 2,    # rev = TRUE: 顛倒顏色
    breaks = c("日", "夜"), 
    labels = c("上半天結算", "下半天結算")
  ) + 
  geom_hline(
    yintercept = 10, 
    color = "#FF8888", 
    linetype = "58"
  ) + 
  annotate(
    "text", x = ymd_h("2019-11-04 18"), y = 11, 
    label = "10次點擊", 
    color = "#FF8888"
  ) + 
  theme_god_hw8 -> 
  godPlot$posterMovieP

poster_toys %>% 
  ggplot(
    aes(
      x = timeStamp, 
      y = 點擊數
    )
  ) + 
  geom_line(
    color = "#dcdcdc", 
    size = 2
  ) + 
  geom_point(
    aes(
      color = 日夜
    ), 
    size = 3
  ) + 
  scale_x_datetime(
    breaks = seq.POSIXt(
      from = ymd_h("2019-11-19 00"), 
      to = ymd_h("2019-11-23 00"), 
      by = "day"
    ), 
    labels = c(
      "11/19", "20", "21", "22", "23"
    )
  ) + 
  # 改legend文字
  scale_color_discrete_qualitative(
    palette = "godpalette_2Qua", nmax = 2,    # rev = TRUE: 顛倒顏色
    breaks = c("日", "夜"), 
    labels = c("上半天結算", "下半天結算")
  ) + 
  geom_hline(
    yintercept = 10, 
    color = "#FF8888", 
    linetype = "58"
  ) + 
  annotate(
    "text", x = ymd_h("2019-11-18 18"), y = 11, 
    label = "10次點擊", 
    color = "#FF8888"
  ) + 
  theme_god_hw8 -> 
  godPlot$posterToysP

poster_Christmas %>% 
  ggplot(
    aes(
      x = timeStamp, 
      y = 點擊數
    )
  ) + 
  geom_line(
    color = "#dcdcdc", 
    size = 2
  ) + 
  geom_point(
    aes(
      color = 日夜
    ), 
    size = 3
  ) + 
  scale_x_datetime(
    breaks = seq.POSIXt(
      from = ymd_h("2019-12-17 00"), 
      to = ymd_h("2019-12-21 00"), 
      by = "day"
    ), 
    labels = c(
      "12/17", "18", "19", "20", "21"
    )
  ) + 
  # 改legend文字
  scale_color_discrete_qualitative(
    palette = "godpalette_2Qua", nmax = 2,    # rev = TRUE: 顛倒顏色
    breaks = c("日", "夜"), 
    labels = c("上半天結算", "下半天結算")
  ) + 
  geom_hline(
    yintercept = 10, 
    color = "#FF8888", 
    linetype = "58"
  ) + 
  annotate(
    "text", x = ymd_h("2019-12-16 18"), y = 11, 
    label = "10次點擊", 
    color = "#FF8888"
  ) + 
  theme_god_hw8 -> 
  godPlot$posterChristmasP

```

# save

```{r}

godPlot$fbMovieP
godPlot$fbToysP
godPlot$fbChristmasP
godPlot$webMovieP
godPlot$webToysP
godPlot$webChristmasP
godPlot$posterMovieP
godPlot$posterToysP
godPlot$posterChristmasP

#save(godPlot, file = "rda/homework8PlotLine.Rda")

```








```{r}

# 改legend文字（三個值都要下）

#  scale_color_manual(
#    values = c("red", "blue"), 
#    breaks = c("日", "夜"), 
#    labels = c("上半天結算", "下半天結算")
#  ) 

```








