---
title: "Untitled"
author: "jacky wang"
date: "2019/12/28"
output:
  html_document:
    includes:
      in_header: "fontawesome.html"
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

# windows檔名不要有"-"號

```

```{r package, include=FALSE}

library(readr) #資料匯入
library(dplyr) #資料整理（slice、select、filter、mutate）
library(tidyr) #資料整理（gather、spread）
library(stringr) #處理字串
library(lubridate) #時間資料處理（ymd）
library(ggplot2) #作圖
library(magrittr) # %<>%
library(showtext) #從字型檔讀取字型，並在繪圖時使用

library(grDevices) #不同色彩空間的十六進制代碼呈現（#598C73）
library(scales) #show_col()：螢幕立即顯示顏色
library(colorspace) #調色盤選擇及ggplot應用工具
library(shiny) #支援套件
library(shinyjs) #支援套件

library(sf)
library(osmdata)

```



# <i class="fas fa-ambulance"></i>

```{r}

load("homework8Plot.Rda")
load("homework8_PieChart.Rda")
load("homework8PlotLine.Rda")

```

```{r eval=FALSE}

final_plot_col

ggsave(filename = "bar.svg", plot = final_plot_col)

```

```{r eval=FALSE}

qualitative_hcl(n = 2, h = c(60, 250), c = 71, l = 78, register = "godPalette_2Qua")

godPlot$fbMovieP
godPlot$fbToysP
godPlot$fbChristmasP
godPlot$webMovieP
godPlot$webToysP
godPlot$webChristmasP
godPlot$posterMovieP
godPlot$posterToysP
godPlot$posterChristmasP

ggsave(filename = "fbMovieP.svg", plot = godPlot$fbMovieP)
ggsave(filename = "fbToysP.svg", plot = godPlot$fbToysP)
ggsave(filename = "fbChristmasP.svg", plot = godPlot$fbChristmasP)
ggsave(filename = "webMovieP.svg", plot = godPlot$webMovieP)
ggsave(filename = "webToysP.svg", plot = godPlot$webToysP)
ggsave(filename = "webChristmasP.svg", plot = godPlot$webChristmasP)
ggsave(filename = "posterMovieP.svg", plot = godPlot$posterMovieP)
ggsave(filename = "posterToysP.svg", plot = godPlot$posterToysP)
ggsave(filename = "posterChristmasP.svg", plot = godPlot$posterChristmasP)

```

```{r eval=FALSE}

ggsave(filename = "pieMovie.svg", plot = movie_PieChart)
ggsave(filename = "pieToys.svg", plot = toys_PieChart)
ggsave(filename = "pieChristmas.svg", plot = Christmas_PieChart)

```






