---
title: "stat functions"
author: "jacky wang"
date: "2019/10/23"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

```

```{r package, include=FALSE}

library(readr) #資料匯入
library(dplyr) #資料整理（slice、select、filter、mutate）
library(tidyr) #資料整理（gather、spread）
library(stringr) #處理字串
library(lubridate) #時間資料處理（ymd）
library(ggplot2) #作圖
library(magrittr) # %<>%
library(showtext) #從字型檔讀取字型，並在繪圖時使用

```





# stat functions


```{r import data 1}

barListDa <- list()

barListDa$library2014 <- 
  read_csv("https://www.dropbox.com/s/999hy0u1y98y6ep/library2014.csv?dl=1")

```

```{r}

barListDa$library2014 %<>% 
  mutate(
    學院 = reorder(學院, 學號, length, order=T)
  ) #學院依照各院資料筆數（length(學號)，已依學院分類）排序

barListDa$library2014 %<>% 
  mutate(
    讀者年級 = factor(讀者年級, levels = c(4:1))
  )

```

```{r plot 1-1}

# geom_bar()和stat_count()是一體兩面的

barListDa$library2014 %>% 
  ggplot + 
  geom_bar(
    aes(
      x = 學院
    ), 
    fill = "#5a99b3"
    # default: stat = "count"
  )

barListDa$library2014 %>% 
  ggplot + 
  stat_count(
    aes(
      x = 學院
    ), 
    fill = "#5a99b3"
    # default: geom = "bar"
  )


# geom_XX底下的另外兩個設定：
#   1. stat = "identity" ··· 按照aes
#   2. position = "identity" ··· 按照aes

```

```{r plot 1-2}

barListDa$library2014 %>% 
  ggplot + 
  geom_bar(
    aes(
      x = 學院, 
      y = stat(prop), 
      group = "全校"
    ), 
    fill = "#5a99b3"
  )

barListDa$library2014 %>% 
  ggplot + 
  stat_count(
    aes(
      x = 學院, 
      y = stat(prop),   # stat(<compute variable>)，compute variable有count、prop
      group = "1"
    ), 
    fill = "#5a99b3"
  )

```

## override geom/stat

```{r plot 2-1}

barListDa$library2014 %>% 
  ggplot + 
  geom_bar(
    aes(
      x = 學院, 
      y = stat(prop), 
      group = "全校"
    )
  ) + 
  stat_count(
    aes(
      x = 學院, 
      y = stat(prop), 
      group = "全校", 
      label = round(stat(prop), 2) # geom_text()需要
    ), 
    # override geom：不用"bar"了
    geom = "text", 
    # nudge_y = -0.01 在這裡沒用
  )

barListDa$library2014 %>% 
  ggplot + 
  geom_bar(
    aes(
      x = 學院, 
      y = stat(prop), 
      group = "全校"
    )
  ) + 
  geom_text(
    aes(
      x = 學院, 
      y = stat(prop), 
      group = "全校", 
      label = round(stat(prop), 2) 
    ), 
    # override stat：不用"identity"了，用"count"（stat_count()）才可以算prop
    stat = "count", 
    #有用了，因為物件導向的關係（geom_text()和stat_count()是不同的物件）
    nudge_y = -0.01 
  )

```

## 自創stat函數

```{r import data 3}

set.seed(111)
df_x <- 
  data.frame(
  x=rnorm(500,mean=2,sd=1)
  )

df_x

```

```{r}

df_x %>%
  ggplot() + 
  geom_histogram(
    aes(
      x = x, 
      y = stat(density) # count or density
    )
    # default: stat = "bin"
    # uses 30 bins, not a good default
  ) + 
  stat_function(
    fun = dnorm, args = list(mean = 2, sd = 1)
  ) # 依fun畫圖，用args（arguments）修改fun的內容
    # default: geom = "path"; n = 101 (bin)

```

```{r create stat fun}

# 市場供需圖

market_D <- 
  function(x, a=1, b=-1){
    return(a+b*x)
  }

market_S <- 
  function(x, a=0, b=1){
    return(a+b*x)
  }

df_grids <- 
  data.frame(
    x = seq(0, 1, by = 0.2)
  ) # 用來限制圖的呈現範圍，並設定X軸值以對應Y軸值


DSplot <- list()

df_grids %>%
  ggplot(
    aes(x = x)
  ) + 
  stat_function(
    fun = "market_D"
  ) + 
  stat_function(
    fun = "market_S"
  ) + 
  labs(
    x = "Quantity", 
    y = "Price"
  ) + 
  theme_classic() ->
  DSplot$base

```

```{r}

DSplot$base

#供給增加

DSplot$base + 
  stat_function(
    fun = market_S, args = list(a = -0.25), 
    color = "red"
  ) + 
  scale_y_continuous(
    limits = c(0, 1)
  )

```

```{r}

#畫出social welfare

df_socialW <- 
  data.frame(
    範圍 = seq(0.25, 0.5, by = 0.01)
  ) #先設定social welfare作圖範圍

DSplot$base + 
  stat_summary(
    data = df_socialW, 
    mapping = aes(
      x = 範圍, 
      y = 範圍
    ), 
    fun.ymin = function(z) market_D(z), 
    fun.ymax = function(z) market_S(z),  #用y值（這裡只有一個）計算ymin & ymax
    geom = "ribbon", 
    alpha = 0.3, 
    fill = "red"
  ) -> 
  DSplot$sMethod


# geom_ribbon(): 
#   For each x value, geom_ribbon() displays a y interval defined by ymin and ymax. 
#   x, ymin & ymax are required

# stat_summary(): 
#   operates on unique x
#   x, y are required
#   將同類的x值下的所有y值丟到指定函數，計算plot所要的y, ymin & ymax三個aes mapping


DSplot$base + 
  geom_ribbon(
    data = df_socialW, 
    mapping = aes(
      x = 範圍, 
      y = 範圍
    ), 
    stat = "summary", 
    fun.ymin = function(z) market_D(z), 
    fun.ymax = function(z) market_S(z),
    alpha = 0.3, 
    fill = "green"
  ) -> 
  DSplot$gMethod

```

```{r}

DSplot$sMethod
DSplot$gMethod

DSplot$base + 
  geom_ribbon(
    data = df_socialW, 
    mapping = aes(
      x = 範圍, 
      ymin = market_D(範圍), 
      ymax = market_S(範圍)
    ), 
    alpha = 0.3
  ) #不用stat_summary()

```





# 清理environment

```{r}

rm(list = ls())
remove(barListDa)

```

