---
title: "Maps"
author: "jacky wang"
date: "2019/11/20"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

```

```{r package, include=FALSE}

library(readr) #資料匯入
library(dplyr) #資料整理（slice、select、filter、mutate）
library(tidyr) #資料整理（gather、spread）
library(stringr) #處理字串
library(lubridate) #時間資料處理（ymd）
library(ggplot2) #作圖
library(magrittr) # %<>%
library(showtext) #從字型檔讀取字型，並在繪圖時使用

library(grDevices) #不同色彩空間的十六進制代碼呈現（#598C73）
library(scales) #show_col()：螢幕立即顯示顏色
library(colorspace) #調色盤選擇及ggplot應用工具
library(shiny) #支援套件
library(shinyjs) #支援套件

```


```{r}

library(sf)

```



# 練習：捷運車站

```{r}

#read_sf("sf-MRT/MARK_捷運車站_1080626.shp") -> 
#  sf_MRT_Taiwan

#sf_MRT_Taiwan

```

```{r}

#用老師整理過的資料

load(url("https://www.dropbox.com/s/uvco1te2kbs6o01/MRT_Taipei.Rda?dl=1"))

sf_mrtStops_tpe

```

```{r}

#只取藍線資料並依站號排序

sf_mrtStops_tpe %>% 
  filter(
    str_detect(經過路線, "BL")
  ) %>% 
  mutate(
    站號 = str_extract(
      經過路線, "(?<=BL)[:digit:]+"
    )
  ) %>% 
  arrange(站號) -> 
  sf_mrtStops_blue

sf_mrtStops_blue

```

```{r}

sf_mrtStops_blue %>% 
  ggplot() + 
  geom_sf()

```

```{r}

#引入北台灣資料

load(url("https://www.dropbox.com/s/elnvocol0nnkcc9/sf_northTaiwan.Rda?dl=1"))

```

```{r}

sf_northTaiwan
#與sf_mrtStops_tpe之CRS不同

```

##畫出藍線站點

```{r}

sf_northTaiwan %>% 
  ggplot() + 
  geom_sf() + 
  geom_sf(
    data = sf_mrtStops_blue
  )
#太小了

```

```{r}

sf_northTaiwan %>% 
  ggplot() + 
  geom_sf() + 
  geom_sf(
    data = sf_mrtStops_blue
  ) + 
  coord_sf(
    xlim = c(121.4, 121.7), 
    ylim = c(24.9, 25.1)
  ) + 
  theme_classic()

```

##站點連成路線

###方法一：geom_path()

```{r}

sf_northTaiwan %>% 
  ggplot() + 
  geom_sf() + 
  geom_sf(
    data = sf_mrtStops_blue
  ) + 
  coord_sf(
    xlim = c(121.4, 121.7), 
    ylim = c(24.9, 25.1)
  ) -> 
  plot_blueStops

sf_mrtStops_blue %>% 
  st_coordinates() ->
  blue_coords

plot_blueStops + 
  geom_path(
    data = data.frame(
      X軸 = blue_coords[, "X"], 
      Y軸 = blue_coords[, "Y"]
    ), 
    mapping = aes(
      x = X軸, 
      y = Y軸
    )
  )
#看不到path，因為geom_path()的值與座標值不相稱（只有geom_sf()會繼承CRS）
#下coord_sf()函式時，bbox已被改為座標形式

```

```{r}

ggplot() + 
  geom_path(
    data = data.frame(
      X軸 = blue_coords[, "X"], 
      Y軸 = blue_coords[, "Y"]
    ), 
    mapping = aes(
      x = X軸, 
      y = Y軸
    )
  )
#geom_path()的值非座標形式

```

```{r}

#正確做法

sf_mrtStops_blue %>% 
  st_transform(crs = st_crs(sf_northTaiwan)) -> 
  sf_mrtStops_blue1

sf_mrtStops_blue1 %>% 
  st_coordinates() -> 
  blue_coords1

plot_blueStops + 
  geom_path(
    data = data.frame(
      X軸 = blue_coords1[, "X"], 
      Y軸 = blue_coords1[, "Y"]
    ), 
    mapping = aes(
      x = X軸, 
      y = Y軸
    )
  )


```

###方法二：創造type為linestring的sfc

```{r}

sf_mrtStops_blue %>% 
  st_coordinates() %>% 
  st_linestring() -> 
  sfg_blueLine
#取出藍線座標並存成type為linestring的sfg

sfg_blueLine %>% 
  st_sfc(crs = st_crs(sf_mrtStops_tpe)) -> 
  sfc_blueLine
#將sfg轉成sfc並定義投射

sfc_blueLine

sf_northTaiwan %>% 
  ggplot() + 
  geom_sf() + 
  geom_sf(
    data = sf_mrtStops_blue
  ) + 
  geom_sf(
    data = sfc_blueLine
  ) + 
  coord_sf(
    xlim = c(121.4, 121.7), 
    ylim = c(24.9, 25.1)
  )

```



