---
title: "Grammar of Graphics"
author: "王正評"
date: "9/25/2019"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

```

```{r, include=FALSE}

library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)

```



# ggplot2

grammar of graphics：作圖的文法

```{r graphic 1}

subsetDataTWbank <- read_csv("https://www.dropbox.com/s/t8ulj3d7cgl8jh5/subsetDataTWbank.csv?dl=1")

```

```{r graphic 2}

subsetDataTWbank %>%
  ggplot() +
  geom_line(
    aes(x=西元年月, y=`定存利率-一個月-固定`) #當變數名稱有特殊符號時，用反頓點符號``將變數名稱圈住
  )
# ggplot()為設置畫布
# geom_xxx()為畫上幾何圖示
# aes()為美學對應（資料呈現的方式）


subsetDataTWbank %>%
  ggplot() + 
  geom_point(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  ) + 
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )
#一層一層的疊上去

```

```{r graphic practice 1}

#請由subsetDataTWbank產生以下圖示：
#座標對應：x=定存類型，y=利率
#幾何圖示類型：boxplot

subsetDataTWbank

subsetDataTWbank %>%
  tidyr::gather(
    contains("利率"), 
    key = "定存類型", value = "利率"
  ) ->
  subsetDataTWbank_1

subsetDataTWbank_1


subsetDataTWbank_1 %>%
  ggplot() + 
  geom_boxplot(
    aes(x=定存類型, y=利率, color=定存類型)
  )

# boxplot：由下往上依序為
#          1. Q1-1.5*IQR內的最小資料值（最小非離群值）
#          2. Q1
#          3. Q2（median）
#          4. Q3
#          5. Q3+1.5*IQR內的最大資料值（最大非離群值）

```

```{r graphic 3}

#相同的aes mapping可以移至ggplot()裡

subsetDataTWbank %>%
  ggplot() + 
  geom_point(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  ) + 
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )

subsetDataTWbank %>%
  ggplot(
     aes(x=西元年月,y=`定存利率-一個月-固定`)
  ) + 
  geom_point() + 
  geom_line()

```

```{r graphic 4}

# X=時間，Y=利率，一次畫出不同定存類型的時間趨勢

subsetDataTWbank_1 %>%
 ggplot() + 
  geom_line(
    aes(
      x=西元年月, 
      y=利率, 
      color=定存類型
    )
  )

```

```{r graphic 5}

#不跟資料對應的呈現改變（整體改變）

subsetDataTWbank %>%
  ggplot() + 
  geom_line(
    aes(x=西元年月, y=`定存利率-一個月-固定`), 
    color = "red", 
    alpha = 0.3, 
    size = 2
  )

# alpha：透明度
# size：大小
# alpha與size是連續的概念，不能用在chr、fctr資料上
# color用在chr、fctr上，會呈現很大的色差；color用在dbl上，會呈現漸層色的樣子
#所以一定要將變數類型調成正確的屬性

```



#字串變數


##類別資料

```{r factor 1}

subsetDataTWbank_1 %>%
  ggplot() + 
  geom_boxplot(
    aes(
      x = 定存類型, 
      y = 利率, 
      color = 定存類型, 
    )
  )

subsetDataTWbank_1 %>%
  str()
#定存類型是chr

subsetDataTWbank_1$定存類型 %>% 
  as.factor() %>% 
  levels()
#資料排序是正常的。若不正常，可由以下方式修改

subsetDataTWbank_1 %>%
  mutate(
    定存類型 = factor(
      定存類型, 
      levels=c("定存利率-一個月-固定", "定存利率-二年期-固定", "定存利率-三年期-固定")
    ) 
  ) -> 
  subsetDataTWbank_2

subsetDataTWbank_2$定存類型 %>%
  levels()

```


##時間資料

```{r date 1}

twCalendar <- c("民國88年11月1日","民國88年12月1日","民國89年1月1日")

```

```{r date 2}

#先將非西元日期字串改成西元日期字串
#然後西元日期字串使用lubridate套件改成date屬性

twCalendar %>%
  stringr::str_extract_all("[:digit:]+") %>% 
  # 取出字串中的數字部份當x向量
  # 打View()用來阻斷pipe，看先前程式跑了什麼
  purrr::map_chr(
    function(x) {
      x1 = as.integer(x[[1]])+1911
      x[[1]] = as.character(x1)
      stringr::str_c(x,collapse="-")
    }
  ) -> 
  westernCalendar
# 將每個日期的「年」由字串轉成整數，加上1991，再轉回字串與「月、日」合併，成為yyyy-mm-dd的格式

westernCalendar


westernCalendar %>%
  lubridate::ymd() -> datetimeCalendar

class(datetimeCalendar)

```

```{r date practice 1}

subsetDataTWbank %>%
  select(
    -西元年月
  ) ->
  TwBank

```

```{r date practice 1-1}

TwBank %>% 
  mutate(
    年月 = 年月 %>% 
      stringr::str_extract_all("[:digit:]+") %>% 
      purrr::map_chr(
        function(x) {
          x1 = as.integer(x[[1]])+1911
          x[[1]] = as.character(x1)
          stringr::str_c(x,collapse="-")
        }
      )
  ) -> TwBank_1

TwBank_1 %>%
  mutate(
    年月 =  stringr::str_c(年月, "01",sep="-")
  ) ->
  TwBank_2

TwBank_2 %>% 
  transmute(
    銀行, 
    西元年月日 = lubridate::ymd(年月), 
    `定存利率-一個月-固定`, 
    `定存利率-二年期-固定`, 
    `定存利率-三年期-固定`
  ) ->
  TwBank_end
  
TwBank
TwBank_1
TwBank_2
TwBank_end

```






