---
title: "osmdata"
author: "jacky wang"
date: "2019/11/27"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

# windows檔名不要有"-"號

```

```{r package, include=FALSE}

library(readr) #資料匯入
library(dplyr) #資料整理（slice、select、filter、mutate）
library(tidyr) #資料整理（gather、spread）
library(stringr) #處理字串
library(lubridate) #時間資料處理（ymd）
library(ggplot2) #作圖
library(magrittr) # %<>%
library(showtext) #從字型檔讀取字型，並在繪圖時使用

library(grDevices) #不同色彩空間的十六進制代碼呈現（#598C73）
library(scales) #show_col()：螢幕立即顯示顏色
library(colorspace) #調色盤選擇及ggplot應用工具
library(shiny) #支援套件
library(shinyjs) #支援套件

library(sf)
library(osmdata)
source(file = "D:/Users/User/Documents/GitHub/Rfunction/osmGeomRename.R")

```



# osmdata

OSM: Open Street Map （向量資料）; link: <https://www.openstreetmap.org>

步驟：1. 連結至OSM
      2. 搜尋區域
      3. 按「匯出」
      4. 由最左邊開始逆時針

```{r}

library(osmdata)

```

## overpass query

步驟：1. 連結至OSM
      2. 搜尋區域
      3. 按「匯出」
      4. bbox由最左邊開始逆時針貼上


key-value(osm feature)查詢：<https://wiki.openstreetmap.org/wiki/Map_Features>

```{r}

bbox_NTPU <- opq(
  bbox = c(121.3583, 24.9381, 121.3771, 24.9483)
)

bbox_NTPU %>% 
  add_osm_feature(
    key = "building", value = "residential"
  ) %>% 
  osmdata_sf() -> 
  multiSf_NTPU #很多sfo在內

multiSf_NTPU$osm_polygons %>% 
  ggplot() + 
  geom_sf()

```



# 20191127正課

## 網頁下載

從網頁上直接匯出osm檔來繪圖
優點：簡單又直覺
缺點：資料量太大（一次匯出所有圖層）

### 練習：國父紀念館

```{r}

#dir.create("osmDownload")

#查看有哪些圖層
st_layers("osmDownload/map_SYSmemorialHall.osm")

#取出line圖層資料（為sfo）
st_read("osmDownload/map_SYSmemorialHall.osm", layer="lines") -> 
  sf_SYSmemorialHall_lines 

sf_SYSmemorialHall_lines

```

```{r}

sf_SYSmemorialHall_lines %>% 
  ggplot() + 
  geom_sf()

sf_SYSmemorialHall_lines %>% 
  filter(
    !is.na(name)    # !: not
  ) %>% 
  ggplot() + 
  geom_sf()

```

```{r}

st_read("osmDownload/map_SYSmemorialHall.osm",layer="points") -> 
  sf_SYSmemorialHall_points

sf_SYSmemorialHall_points %>% 
  ggplot() + 
  geom_sf()

```

```{r}

st_read(dsn = "osmDownload/map_SYSmemorialHall.osm", layer = "multipolygons") -> 
  sf_SYSmemorialHall_multipolygons

sf_SYSmemorialHall_multipolygons %>% 
  ggplot() + 
  geom_sf() + 
  theme_classic() -> 
  plot_SYSmemorialHall_multipolygons

plot_SYSmemorialHall_multipolygons + 
  geom_sf(
    data = sf_SYSmemorialHall_points %>% 
      filter(
        !is.na(name)
      )
  ) + 
  geom_sf(
    data = sf_SYSmemorialHall_lines %>% 
      filter(
        !is.na(name)
      )
  ) + 
  coord_sf(
    xlim = c(121.555, 121.57), 
    ylim = c(25.033, 25.047)
  )

```

### 練習：臺北車站

```{r}

st_layers(dsn = "osmDownload/tpeMainStation.osm") #查看有哪些layer


st_read(dsn = "osmDownload/tpeMainStation.osm", layer = "multipolygons") -> 
  sf_tpeMainStation_mulPoly #匯入multipolygon資料

st_read(
  dsn = "osmDownload/tpeMainStation.osm", 
  layer = "points"
) -> 
  sf_tpeMainStation_pt

```

```{r}

sf_tpeMainStation_mulPoly %>% 
  ggplot() + 
  geom_sf() + 
  geom_sf(
    data = sf_tpeMainStation_mulPoly %>% 
      filter(
        name == "臺北車站"
      ), 
    fill = "lightblue"
  ) + 
  geom_sf(
    data = sf_tpeMainStation_pt %>% 
      filter(
        !is.na(highway)
      ), 
    aes(
      fill = highway, 
      color = highway
    )
  ) + 
  geom_sf_label(
    data = sf_tpeMainStation_mulPoly %>% 
      filter(
        name == "臺北車站"
      ), 
    aes(label = "車站大樓"), 
    size = 8/.pt
  ) + 
  coord_sf(
    xlim = c(121.512, 121.52), 
    ylim = c(25.045, 25.052)
  ) + 
  theme_classic() -> 
  plot_tpeMainStation

plot_tpeMainStation

#plot_tpeMainStation %>% 
#  ggsave(filename = "tpeMainStation.png") #存成png檔（or 對圖點右鍵）

```

```{r}

#load(url("https://www.dropbox.com/s/pyinluminj0kb98/homework6.Rda?dl=0"))
#   從dropbox匯入資料
#     改「...dl=1」：匯入資料

```

```{r}

#st_centroid()
#st_buffer()

```


## overpass query

步驟：1. 連結至OSM
      2. 搜尋區域
      3. 按「匯出」
      4. bbox由最左邊開始逆時針貼上


key-value(osm feature)查詢：<https://wiki.openstreetmap.org/wiki/Map_Features>

優點：不會像「網頁下載」一次匯入所有資訊
缺點：要先想好要畫什麼

### 練習：國父紀念館

```{r}

#建立bbox
opq(bbox = c(121.55611, 25.03715, 121.56554, 25.04224)) -> 
  bbox_SYSmemorialHall1

#選擇要加入的feature，並轉成sf檔
bbox_SYSmemorialHall1 %>% 
  add_osm_feature(
    key = "tourism", 
    value = "attraction" 
  ) %>% 
  osmdata_sf() -> 
  multiSf_SYSmemorialHall1

multiSf_SYSmemorialHall1$osm_polygons %>% 
  ggplot() + 
  geom_sf() + 
  theme_classic()

```

### 練習：臺北市

```{r}

opq(
  bbox = c(121.4616,25.1050,121.6058,24.9894) 
) -> 
  bbox_tpe

bbox_tpe %>% 
  add_osm_feature(
    key="admin_level", value="5"  # Boundary類
  ) %>%
  osmdata_sf() -> multiSf_tpe
# link: https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative

multiSf_tpe$osm_multipolygons -> 
  sf_tpe # sf class

#sf_tpe %>% 
#  ggplot() + 
#  geom_sf()
#Error: variable names are limited to 10000 bytes

```

```{r}

#source("https://www.dropbox.com/s/8ndtvzqbdb4cb93/data_visulaization_pk.R?dl=1")
#此函式用以更改geometry下元素的命名（太長，超過R內定可容忍長度了）

sf_tpe %>% 
  osm_geom_rename() %>% 
  ggplot() + 
  geom_sf()

#下載回來自己用

#download.file(url = "https://www.dropbox.com/s/8ndtvzqbdb4cb93/data_visulaization_pk.R?dl=1", destfile = "osmGeomRename.R")

#匯入函式（source只能匯入.R檔）
#source(file = "D:/Users/User/Documents/GitHub/Rfunction/osmGeomRename.R")


```








```{r}

map_taipei_subway$osm_lines %>%
  mutate(
    length=st_length(geometry),
    shortname=str_replace(name,"捷運","") %>%
      str_extract("[:graph:]+(?=線)")
  ) -> sf_tpe_mrt

```

```{r}

source("https://www.dropbox.com/s/8ndtvzqbdb4cb93/data_visulaization_pk.R?dl=1")

```


```{r}


sf_tpe_mrt %>%
group_by(
    shortname
  ) %>%
  summarise(
    geometry=st_union(geometry)
  ) %>%
  ungroup() %>%
  na.omit() -> sf_tpe_mrt


sf_tpe_mrt %>%
  ggplot()+geom_sf(
    aes(color=shortname, fill=shortname), size=1
  ) +
  geom_sf_text(
    aes(label=shortname)
  )+
  labs(title="台北捷運路線圖")


```


