---
title: "homework6"
author: "jacky wang"
date: "2019/12/2"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(readr) #資料匯入
library(dplyr) #資料整理（slice、select、filter、mutate）
library(tidyr) #資料整理（gather、spread）
library(stringr) #處理字串
library(lubridate) #時間資料處理（ymd）
library(ggplot2) #作圖
library(magrittr) # %<>%
library(showtext) #從字型檔讀取字型，並在繪圖時使用

```



```{r}

# R複製貼上的方法

library(clipr)

read_clip() #-> cv

#cv

```

```{r}

#複製貼上表格

library(psych)

psych::read.clipboard() #-> df_cv

#df_cv

```

```{r}

#改橫式書寫為直式

load("D:/Users/User/Documents/GitHub/course-practice-datavisualization/homework/homework4.Rda")

graphListP <- list()



graphListD$Case_10_result_eV %>% 
  ggplot(
    aes(
      x = 六都, 
      y = `同意比例（同意票／有效票）`
    )
  ) + 
  geom_col(
    aes(
      alpha = `同意比例（同意票／有效票）`
    ), 
    width = 0.5, 
    fill = "#FF72C7"
  ) -> 
  graphListP$base

graphListP$base + 
  coord_flip() +  
  scale_x_discrete(
    limits = c("高雄市", "臺南市", "臺中市", "桃園市", "新北市", "臺北市"), 
    labels = c(
      "臺北市" = paste("臺", "北", "市", sep = "\n"), 
      "新北市" = paste("新", "北", "市", sep = "\n"),
      "桃園市" = paste("桃", "園", "市", sep = "\n"), 
      "臺中市" = paste("臺", "中", "市", sep = "\n"), 
      "臺南市" = paste("臺", "南", "市", sep = "\n"), 
      "高雄市" = paste("高", "雄", "市", sep = "\n")
    )
  ) + 
  scale_y_continuous(
    limits = c(0, 0.75), 
    labels = function(x) x*100
  ) + 
  scale_alpha(
    range = c(1, 0.2)
  ) -> 
  graphListP$adjust_scale
  
graphListP$adjust_scale + 
  xlab(
    label = c("六都" = paste("直", "轄", "市", sep = "\n"))
  ) + 
  theme(
    axis.title.y = element_text(angle = 0, vjust = 0.5)
  )
# label(s) = c("原名" = paste("XXX", "XXX", sep = "\n"))

# View(paste) #看函式

```

