---
title: "Annotation and Maps"
author: "jacky wang"
date: "2019/10/30"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

```

```{r package, include=FALSE}

library(readr) #資料匯入
library(dplyr) #資料整理（slice、select、filter、mutate）
library(tidyr) #資料整理（gather、spread）
library(stringr) #處理字串
library(lubridate) #時間資料處理（ymd）
library(ggplot2) #作圖
library(magrittr) # %<>%
library(showtext) #從字型檔讀取字型，並在繪圖時使用

```





# 地圖基本元素


```{r}

exampleList <- list()
mapListD <- list()
mapListP <- list()

```


```{r}

ggplot() + 
  theme_bw() +      #用來畫格線的theme
  scale_x_continuous(
    limits = c(0,6), 
    expand = expand_scale(add = c(0,0))  # expand: 調整格線以外預留寬度
  ) + 
  scale_y_continuous(
    limits = c(0,6), 
    expand = expand_scale(mult = c(0,0)) # mult: 預留 格線總長度*0 的寬度; add: 預留 0 的寬度
  ) ->
  exampleList$myGrids

exampleList$myGrids

```

point: 如景點位置；geom_point
line: 如河流； geom_path
polygon: 如臺北市範圍界線；geom_polygon

```{r}

#多數地理資料是用matrix來存的

matrix_eg1 <-     #      x y     座標
  rbind(          #如  /     \
    c(1,5),       #   |  1 5  |
    c(2,1),       #   |  2 1  |
    c(5,1),       #   |  5 1  |
    c(5,5)        #   |  5 5  |
  )               #    \     /

matrix_eg1

matrix_eg1 %>% 
  as.data.frame()  # V1為x座標，V2為y座標

```

```{r}

exampleList$myGrids +
  geom_point(
    data = as.data.frame(matrix_eg1), 
    aes(x = V1, y = V2)
  ) -> 
  exampleList$pointEg

exampleList$myGrids +
  geom_path(
    data = as.data.frame(matrix_eg1), 
    aes(x = V1, y = V2)
  ) -> 
  exampleList$pathEg

exampleList$myGrids +
  geom_polygon(
    data = as.data.frame(matrix_eg1), 
    aes(x = V1, y = V2)
  ) -> 
  exampleList$polygonEg

ggpubr::ggarrange(
  exampleList$pointEg, exampleList$pathEg, exampleList$polygonEg,
  ncol=3
)

```

## 北台灣範例

```{r}

mapListD$df_northTW <- read_csv("https://www.dropbox.com/s/6uljw24zkyj7avs/df_geo_northTW.csv?dl=1")

```

```{r}

mapListD$df_northTW %>% 
  filter(
    COUNTYNAME == "新北市"
  ) %>%
  ggplot() + 
  geom_polygon(
    aes(
      x = x, 
      y = y
    ), 
    fill = "green"
  ) -> 
  mapListP$newTaipeiCity
mapListP$newTaipeiCity

mapListD$df_northTW %>% 
  filter(
    COUNTYNAME == "新北市"
  ) %>%
  ggplot() + 
  geom_point(
    aes(
      x = x, 
      y = y
    ), 
    color = "blue"
  )

mapListD$df_northTW %>% 
  filter(
    COUNTYNAME == "新北市"
  ) %>%
  ggplot() + 
  geom_path(
    aes(
      x = x, 
      y = y
    ), 
    color = "blue"
  )

```

```{r}

mapListP$newTaipeiCity + 
  theme_bw()

```

## polygon with holes

```{r}

exampleList$polygonEg

matrix_eg1_hole <- 
  rbind(
    c(2,4), 
    c(3,2), 
    c(4,3)
  )

exampleList$polygonEg + 
  geom_polygon(
    data = as.data.frame(matrix_eg1_hole), 
    mapping = aes(x = V1, y = V2), 
    fill = "white"
  ) 
#這是假像的解決問題，洞並沒有透出底部格線

```

```{r}

#設定geom_polygon(..., group = ,subgroup = )所須變數（總區與各分區）
matrix_eg1 %>% 
  as.data.frame() %>% 
  mutate(
    sub_id = "1", 
    group_id = "a"
  ) ->
  exampleList$df_1 

matrix_eg1_hole %>% 
  as.data.frame() %>% 
  mutate(
    sub_id = "2", 
    group_id = "a"
  ) -> 
  exampleList$df_2

bind_rows(
  exampleList$df_1, 
  exampleList$df_2
) -> 
  exampleList$df_all


# 真正解決問題的方法
exampleList$myGrids + 
  geom_polygon(
    data = exampleList$df_all, 
    mapping = aes(
      x = V1, 
      y = V2, 
      group = group_id, subgroup = sub_id
    )
  )

```

### 北台灣範例（新北市）

```{r}

#請畫出正確的新北市地圖

mapListD$df_northTW %>% 
  filter(
    COUNTYNAME %in% c("臺北市", "新北市")
  ) %>%
  mutate(
    group_id = "新北"
  ) -> 
  mapListD$df_northTW_id

mapListD$df_northTW_id %>% 
  ggplot() + 
  geom_polygon(
    aes(
      x = x, 
      y = y, 
      group = group_id, subgroup = COUNTYNAME
    )
  ) + 
  theme_bw()
  #內圈會自動變成hole

```

# annotate

標註一次性的註解


```{r}

# 用顏色來區分區域

mapListD$df_northTW %>% 
  ggplot() + 
  geom_polygon(
    aes(
      x = x, 
      y = y, 
      fill = COUNTYNAME
    ), 
    color = "azure4"
  ) + 
  theme_bw() ->
  mapListP$bigTaipei

```

```{r}

mapListD$thisTaipei <- 
  data.frame(
    x = c(121.55, 121.7), 
    y = c(25.05, 25.25)
  )

mapListP$bigTaipei + 
  geom_path(
    data = mapListD$thisTaipei, 
    mapping = aes(
      x = x, 
      y = y
    ), 
    size = 1
  ) + 
  annotate(
    "text",  # geom可以是"point"、"text"、"rect"……
    x = 121.7, y = 25.25, label = "臺北市", fontface="bold",  
    vjust = 0
  )
#以「北」的中心為座標點
# vjust、hjust只能下0～1，如果位置仍不準確，應該調整座標值，而非用超過範圍的數值
# default: vjust = 0.5, hjust = 0.5

```

## 圖片

```{r}

library(magick) #處理影像的套件

```

```{r}

image_read("https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/2450df20386177.562ea7d13f396.jpg") -> 
  mapListD$taipei101

```

```{r}

image_info(mapListD$taipei101) #觀察圖片的高寬比，使縮放時比例不變

taipei101_asp <- 
  image_info(mapListD$taipei101)$height/image_info(mapListD$taipei101)$width

```

```{r}

#檢查圖片底色是否為透明

theme_bw() + 
  theme(
    panel.background = element_rect(fill = "cyan4")
  ) -> 
  theme_checkBack

image_ggplot(mapListD$taipei101) + 
  theme_checkBack
#非透明

```

image_fill(image, color, point = "+1+1", fuzz = 0, refcolor = NULL)

point: 倒顏料的位置（小畫家）；注意Y軸是顛倒的
fuzz: 邊界定義的模糊度，0（嚴謹）～100（鬆散）

```{r}

image_fill(mapListD$taipei101, "transparent", point = "+100+100", fuzz = 0) %>%
  image_ggplot() + 
  theme_checkBack #邊界定義太過嚴謹

image_fill(mapListD$taipei101, "transparent", point = "+100+100", fuzz = 15) %>%
  image_ggplot() + 
  theme_checkBack

```

```{r}

#轉成raster（矩陣）資料

image_fill(mapListD$taipei101, "none", point = "+100+100", fuzz = 15) -> 
  mapListD$taipei101_noBack

mapListD$taipei101_noBack %>% 
  as.raster() -> 
  mapListD$taipei101_raster

mapListD$taipei101_raster[100,300]

```

```{r}

taipei101_position <- 
  c(lon=121.5622782,lat=25.0339687)  # Taipei經緯度


taipei101_width <- 0.13  # Taipei101在地圖佔寬

mapListP$bigTaipei + 
  annotation_raster(
    raster = mapListD$taipei101_raster, 
    xmin = taipei101_position[1]-taipei101_width/2, 
    xmax = taipei101_position[1]+taipei101_width/2, 
    ymin = taipei101_position[2]-taipei101_asp*taipei101_width/2, 
    ymax = taipei101_position[2]+taipei101_asp*taipei101_width/2
  ) -> 
  mapListP$bigTaipei_image
 
```

```{r}

# 調低解析度（小圖不用太高的解析度）

image_scale(mapListD$taipei101_noBack, "200") -> 
  mapListD$taipei101_noBacksm
  # Taipei寬解析度調整成200，並維持aspect ratio

mapListD$taipei101_noBacksm %>% 
  as.raster() -> 
  mapListD$taipei101_rastersm

mapListP$bigTaipei + 
  annotation_raster(
    mapListD$taipei101_rastersm, 
    taipei101_position[1] - taipei101_width/2, 
    taipei101_position[1] + taipei101_width/2, 
    taipei101_position[2] - taipei101_asp*taipei101_width/2, 
    taipei101_position[2] + taipei101_asp*taipei101_width/2
  ) -> 
  mapListP$bigTaipei_imagesm

mapListP$bigTaipei_image
mapListP$bigTaipei_imagesm

```

