---
title: "stat functions"
author: "jacky wang"
date: "2019/10/16"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

```

```{r package, include=FALSE}

library(readr) #資料匯入
library(dplyr) #資料整理（slice、select、filter、mutate）
library(tidyr) #資料整理（gather、spread）
library(stringr) #處理字串
library(lubridate) #時間資料處理（ymd）
library(ggplot2) #作圖
library(magrittr) # %<>%
library(showtext) #從字型檔讀取字型，並在繪圖時使用

```



# geom_rect：事件分析

```{r import data 1}

load(
  url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework2/graphData_homework2_005.Rda?raw=true")
)

graphData$data

```

```{r plot 1}

godplot <- list()

graphData$data %>%
  ggplot() + 
  geom_line(
    aes(
      x = 年份, 
      y = 毛額, 
      linetype = 國民所得_儲蓄_投資毛額
    )
  ) + 
  theme_classic() + 
  theme(
    legend.position = "none"
  ) -> 
  godplot$base
  
#標示事件的時間區間用
data.frame(
  start = c(2008, 2013), 
  end = c(2009, 2014), 
  floor = c(-Inf, -Inf), 
  celling = c(Inf, Inf), 
  name = c("次貸危機", "歐債危機")
) -> 
  graphData$event

#圖例說明用
graphData$data %>% 
  group_by(`國民所得_儲蓄_投資毛額`) %>% 
  summarise(
    最後一筆 = last(毛額)
  ) %>% 
  ungroup() %>% 
  mutate(
    分類 = c("國民所得毛額", "國民儲蓄毛額", "國民投資毛額")
  ) -> 
  graphData$legend


godplot$base + 
  geom_rect(
    data = graphData$event, 
    mapping = aes(
      xmin = start, 
      xmax = end, 
      ymin = floor, 
      ymax = celling
    ), 
    alpha = 0.2
  ) -> 
  godplot$add_event


godplot$add_event + 
  geom_text(
    data = graphData$legend, 
    mapping = aes(
      x = 2017, 
      y = 最後一筆, 
      label = 分類
    ), 
    nudge_y = 8000
  ) + 
  geom_text(
    data = graphData$event, 
    mapping = aes(
      x = (start+end)/2, 
      y = 180000, 
      label = name
    )
  ) -> 
  godplot$add_text

```

```{r plot 1-1}

godplot$base
godplot$add_text

```

```{r plot 1-2}

#錯誤作法
graphData$data %>%
  ggplot(
    aes(
      x=年份, 
      y=毛額
    )
  ) + 
  geom_line(
    aes(
      linetype=國民所得_儲蓄_投資毛額
    )
  ) + 
  theme_classic() + 
  theme(
    legend.position = "none"
  ) + 
  geom_rect(
    data = graphData$event, 
    aes(
      xmin = start, 
      xmax = end, 
      ymin = floor, 
      ymax = celling
    ), 
    alpha = 0.2, 
    inherit.aes = F
  )
# ggplot()裡的aes()會套用到所有geom內，因geom_rect()裡的data沒有相同x、y變數導致錯誤
#在geom_rect()裡使用 inherit.aes = F 使它不受ggplot()影響

```





# 長條圖


## geom_col

```{r import data 2}

graphListD_2 <- list()
graphListP_2 <- list()

graphListD_2$startSalaryTopCat <- 
  read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/startSalaryTopCat.csv")

graphListD_2$startSalaryTopCat

```

```{r data wrangling 2}

graphListD_2$startSalaryTopCat$大職業別[3:7] %>% 
  str_c(., collapse = " ',' ")
#方便複製貼上
  
graphListD_2$startSalaryTopCat %>% 
  filter(
    大職業別 %in% c(
      '礦業及土石採取業', '製造業', '電力及燃氣供應業', '用水供應及污染整治業', '營造業'
    )
  ) -> 
  graphListD_2$startingSalary_industry

```

```{r}

graphListD_2$startingSalary_industry %>%  
  ggplot() + 
  geom_col(
    aes(
      x = 大職業別, 
      y = `經常性薪資-薪資`
    )
  ) -> 
  graphListP_2$industry_salary

graphListP_2$industry_salary

```

### 改變順序

```{r}

#想依經常性薪資由小到大排列

#作法一：資料整理時
graphListD_2$startingSalary_industry %<>%
  mutate(
    大職業別ordered = stats::reorder(
      大職業別, `經常性薪資-薪資`, order=T
    ) # reorder(欲排變數, 依某變數大小, order=T才會排)，產生一 ordered factor 變數
  )

graphListD_2$startingSalary_industry %>%
  ggplot()+
  geom_col(
    aes(
      x = 大職業別ordered, 
      y = `經常性薪資-薪資`
    )
  ) -> 
  graphListP_2$industry_salary_ordered

graphListP_2$industry_salary_ordered
graphListP_2$industry_salary
  
```

```{r}

#作法二：作圖時

graphListP_2$industry_salary

graphListD_2$startingSalary_industry %>% 
  ggplot() + 
  geom_col(
    aes(
      x = reorder(大職業別, `經常性薪資-薪資`, order = T), 
      y = `經常性薪資-薪資`
    )
  )

```

```{r}

#作法三：使用scale_x_discrete()中的limits

graphListP_2$industry_salary

reorder(
  graphListD_2$startingSalary_industry$大職業別, 
  graphListD_2$startingSalary_industry$`經常性薪資-薪資`, 
  order = T
  ) %>% 
  levels() -> 
  indSalOrder #要下字串給limits

graphListP_2$industry_salary + 
  scale_x_discrete(
    limits = indSalOrder
  )

```

### 改變width

```{r}

#先建立一個基本ggplot方便後面疊加
graphListD_2$startingSalary_industry %>% 
  ggplot(
    aes(
      x = 大職業別ordered, 
      y = `經常性薪資-薪資` 
    )
  ) -> 
  graphListP_2$ggplot_ordered


graphListP_2$ggplot_ordered + 
  geom_col(
    width = 0.6
  )

```

```{r}

# theme(..., aspect.ratio = )：改變整個圖的高寬比例

graphListP_2$industry_salary_ordered + 
  theme(
    aspect.ratio = 1/2
  )

#再來調width
graphListP_2$ggplot_ordered + 
  geom_col(
    width = 0.6
  ) + 
  theme(
    aspect.ratio = 1/2
  )

graphListP_2$ggplot_ordered + 
  geom_col(
    width = 0.6
  )

```

```{r}

graphListP_2$industry_salary_ordered + 
  theme(
    aspect.ratio = 1/0.8
  )
#字疊在一起了

graphListP_2$industry_salary_ordered + 
  theme(
    aspect.ratio = 1/0.8, 
    axis.text.x = element_text(angle = 20) #讓字旋轉20度
  ) + 
  theme(
    axis.text.x = element_text(hjust = 0.9, vjust = 1)
  ) # horizontal justification (in [0, 1])
    # vertical justification (in [0, 1])
    # 調整angle後vjust、hjust會變得很奇怪

```

### 座標旋轉

使用coord_flip()

```{r}

graphListP_2$industry_salary_ordered + 
  coord_flip()

```


## geom_bar

```{r import data 3}

barListDa <- list()
barListPo <- list()

barListDa$library2014 <- 
  read_csv("https://www.dropbox.com/s/999hy0u1y98y6ep/library2014.csv?dl=1")

```

```{r data wrangling 3}

# between()用法
barListDa$library2014 %>%
  filter(
    讀者年級 %>% between(1,2)
  )

#先將學院依各院人數多寡排序

barListDa$library2014 %<>% 
  mutate(
    學院 = reorder(學院, 學號, length, order=T)
  ) #學院依照各院資料筆數（length(學號)，已依學院分類）排序

barListDa$library2014 %<>% 
  mutate(
    讀者年級 = factor(讀者年級, levels = c(4:1))
  )

```

```{r}

barListDa$library2014 %>% 
  ggplot() + 
  geom_bar(
    aes(x = 學院), 
    fill="#5A99B3", 
    width=0.7
  ) # y軸由geom_bar()去呼叫stat_count()計算分類個數

barListDa$library2014 %>% 
  ggplot + 
  geom_bar(
    aes(
      x = 學院, 
      fill = 讀者年級
    ), 
    width = 0.7
  ) 

```

### position

dodge：躲避
fill：填滿（標準化成同高度，呈現比重變化用）
stack：疊上

```{r}

barListDa$library2014 %>% 
  ggplot() + 
  geom_bar(
    aes(
      x = 學院, 
      fill = factor(
        讀者年級, 
        levels = c("1", "2", "3", "4")
      ) 
    ), 
    width=0.7, 
    position = "dodge"
  ) + 
  scale_fill_discrete(
    guide = guide_legend(title = "讀者年級", title.position = "bottom")
  ) 
# guide: A function used to create a guide or its name. 
# call to a guide function ( i.e. guide_colourbar() or guide_legend() )
# guide_legend(): 
#   title: A character string or expression indicating a title of guide.
#   title.position: A character string indicating the position of a title.

barListDa$library2014 %>% 
  ggplot() + 
  geom_bar(
    aes(
      x = 學院, 
      fill = 讀者年級
    ), 
    width=0.7, 
    position = "fill"
  ) 

barListDa$library2014 %>% 
  ggplot() + 
  geom_bar(
    aes(
      x = 學院, 
      fill = 讀者年級
    ), 
    width=0.7, 
    position = "stack"
  ) 

```


## geom_histogram

直方圖的常見作法是將連續變數

1. 先切成一段段不重疊的數值區間（bin）

2. 以每個bin為長條圖X軸的類別變數，進行作圖

```{r import data 4}

set.seed(2019) #用以固定後續隨機變數的產生
x <- rnorm(100)
head(x)

ggplot2::cut_interval(x, n = 8) ->
  x_interval
#以隨機變數的min和max為範圍等距切8段，並將各隨機變數值轉成所在區間值

levels(x_interval) # x_interval為類別變數，總共有8類

xNorm <- data.frame(
  x = x, 
  xInterval = x_interval
)

```

```{r}

xNorm %>% 
  ggplot() + 
  geom_bar(
    aes(x = x_interval)
  )
#錯誤的作法：
#  1. 連續的資料中間不該有空白
#  2. 不應該以各組次數為bar的高度，要以各組占比為bar的高度

```

```{r}

xNorm %>% 
  ggplot() + 
  geom_histogram(
    aes(x = x)
  ) # default（默認）為30個bin

xNorm %>% 
  ggplot() + 
  geom_histogram(
    aes(x = x), 
    bins = 8
  )

xNorm %>% 
  ggplot() + 
  geom_histogram(
    aes(x = x), 
    bins = 200
  ) #資料量愈大，optimal bin應該要愈大（連續的資料不應該有過大的組距）

```

```{r}

#原則上「樣本越大」、「資料越集中」則bin數目越多
#這裡依Freedman-Diaconis rule選bin數

OptiBins <- grDevices::nclass.FD(xNorm$x)

xNorm %>% 
  ggplot() + 
  geom_histogram(
    aes(x = x), 
    bins = OptiBins
  ) 

```

```{r}

xNorm %>% 
  ggplot() + 
  geom_density(
    aes(x = x)
  )
#直方圖是最不扭曲連續資料呈現的圖，也是一般的人看得懂的圖

```


## stat function

```{r}

barListDa$library2014 %>%
  ggplot() + 
  geom_bar(
    aes(
      x = 學院
      #y預設為stat(count)
    ), 
    fill = "#5A99B3", 
    width = 0.7
  )

barListDa$library2014 %>%
  ggplot() + 
  geom_bar(
    aes(
      x = 學院, 
      y = stat(count)
    ), 
    fill = "#5A99B3", 
    width = 0.7
  )

# stat(prop)
barListDa$library2014 %>%
  ggplot() + 
  geom_bar(
    aes(
      x = 學院, 
      y = stat(prop)   # prop: groupwise proportion（以x分組）
    ), 
    fill = "#5A99B3", 
    width = 0.7
  )

barListDa$library2014 %>%
  ggplot() + 
  geom_bar(
    aes(
      x = 學院, 
      y = stat(prop), 
      group = "全校"   #隱性創造一個group變數，值為「全校」
    ), 
    fill = "#5A99B3", 
    width = 0.7
  )

```

