---
title: "ggplot2"
author: "王正評"
date: "9/25/2019"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = F, eval=T)

```


```{r}

library(readr)
subsetDataTWbank <- read_csv("https://www.dropbox.com/s/t8ulj3d7cgl8jh5/subsetDataTWbank.csv?dl=1")

```


```{r}

library(ggplot2)

subsetDataTWbank %>%
  ggplot() + 
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  ) # aes 美學


subsetDataTWbank %>%
  ggplot() + 
  geom_point(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  ) + 
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )

```


```{r}

subsetDataTWbank %>%
  gather(contains("利率"), 
       key = "類別", value = "利率") ->
  subsetDataTWbank_1

subsetDataTWbank_1 %>%
  ggplot() + 
  geom_boxplot(
    aes(x=類別, y=利率, color=類別)
  )

```

```{r}

subsetDataTWbank_1 %>%
  ggplot() + 
  geom_line(
    aes(x=西元年月, y=利率, color=類別)
  )

```

```{r}

subsetDataTWbank %>%
  ggplot() + 
  geom_line(
    aes(x=西元年月, y=`定存利率-一個月-固定`), 
    color = "red", 
    alpha = 0.3, 
    size = 3
  )

```


```{r}

subsetDataTWbank_1

subsetDataTWbank_1$類別 %>% 
  as.factor() %>% 
  levels()

subsetDataTWbank_1 %>%
  mutate(
    類別=factor(類別, 
                  levels=c("定存利率-一個月-固定", "定存利率-二年期-固定", "定存利率-三年期-固定")
                  )
  ) -> subsetDataTWbank_2

subsetDataTWbank_2

```

```{r}

twCalendar <- c("民國88年11月1日","民國88年12月1日","民國89年1月1日")

```

```{r}



```



